INSERT INTO K_USER (ID_USER, DS_NAME, DS_LAST_NAME, QT_AGE) VALUES(1,'Francisco', 'Perez', 45);
INSERT INTO K_USER (ID_USER, DS_NAME, DS_LAST_NAME, QT_AGE) VALUES(2,'Manuel', 'Robles', 23);
INSERT INTO K_USER (ID_USER, DS_NAME, DS_LAST_NAME, QT_AGE) VALUES(3,'Hector', 'Paredes', 19);

INSERT INTO W_PARAM (ID, DS_VALUE) VALUES(1,'http://192.168.100.222:8080/cardsivale/card/');
INSERT INTO W_PARAM (ID, DS_VALUE) VALUES(2,'http://192.168.100.222:8080/cardsivale/card/activate/');